THY-47 removed unused files, cleanup solutions reference
FHU/thywordle pull request #31
Opened 2023-02-27 19:55 UTC by kadenbking

2023-02-27 20:04 UTC, djyarnell0 approved these changes

2023-02-27 20:04 UTC, djyarnell0 commented
Looks good!

2023-02-28 02:31 UTC, kenancasey requested changes

2023-02-28 02:31 UTC, kenancasey commented on src/constants/solutions.ts
> +    reference: '1JOHN 1:1',
I think this should be `1 John 1:1` (with the first space).

2023-03-01 03:49 UTC, kenancasey approved these changes
I think I'm good with this.

2023-03-01 03:53 UTC, merged